// Common emoji shortcode → character mapping. Focused on developer and chat
// emojis — the ones people actually type daily. Not exhaustive; the user noted
// Claude Code's picker also doesn't have all emojis.

export interface EmojiEntry {
    readonly char: string;
    readonly codes: readonly string[]; // multiple shortcodes for the same emoji
}

const EMOJIS: readonly EmojiEntry[] = [
    { char: "😂", codes: ["joy", "laughing", "tears_of_joy"] },
    { char: "❤️", codes: ["heart", "hearts"] },
    { char: "🤣", codes: ["rofl", "rolling_on_the_floor_laughing"] },
    { char: "🥹", codes: ["holding_back_tears"] },
    { char: "♥️", codes: ["heart_suit"] },
    { char: "😍", codes: ["heart_eyes", "in_love"] },
    { char: "😭", codes: ["sob", "crying", "tears"] },
    { char: "😊", codes: ["blush", "smiling"] },
    { char: "😒", codes: ["unamused", "side_eye"] },
    { char: "😘", codes: ["kissing_heart"] },
    { char: "😉", codes: ["wink"] },
    { char: "💕", codes: ["two_hearts"] },
    { char: "😁", codes: ["grin"] },
    { char: "👍", codes: ["+1", "thumbsup", "like"] },
    { char: "👎", codes: ["-1", "thumbsdown", "dislike"] },
    { char: "🖕", codes: ["middle_finger", "flip_off"] },
    { char: "🙏", codes: ["pray", "please", "thanks"] },
    { char: "🤔", codes: ["thinking", "hmm"] },
    { char: "😅", codes: ["sweat_smile", "nervous"] },
    { char: "😱", codes: ["scream", "omg"] },
    { char: "🤗", codes: ["hugging", "hugs"] },
    { char: "😏", codes: ["smirk"] },
    { char: "😢", codes: ["sad", "sad_but_relieved"] },
    { char: "🤷", codes: ["shrug"] },
    { char: "🤷‍♂️", codes: ["man_shrugging"] },
    { char: "🤷‍♀️", codes: ["woman_shrugging"] },
    { char: "✅", codes: ["white_check_mark", "check", "done"] },
    { char: "❌", codes: ["x", "cross", "fail"] },
    { char: "⚠️", codes: ["warning", "caution"] },
    { char: "🔥", codes: ["fire", "hot", "lit"] },
    { char: "💯", codes: ["100", "hundred", "points"] },
    { char: "⭐", codes: ["star"] },
    { char: "🎉", codes: ["tada", "party", "hooray"] },
    { char: "👀", codes: ["eyes", "look"] },
    { char: "🚀", codes: ["rocket", "ship", "deploy"] },
    { char: "💡", codes: ["bulb", "idea"] },
    { char: "🤝", codes: ["handshake", "deal"] },
    { char: "🍀", codes: ["four_leaf_clover", "luck"] },
    { char: "🎯", codes: ["dart", "bullseye", "target"] },
    { char: "💪", codes: ["muscle", "strong", "flex"] },
    { char: "🧠", codes: ["brain", "smart"] },
    { char: "🤡", codes: ["clown", "joke"] },
    { char: "👋", codes: ["wave", "hi", "bye"] },
    { char: "👌", codes: ["ok_hand", "perfect"] },
    { char: "🙌", codes: ["raised_hands", "hallelujah"] },
    { char: "👏", codes: ["clap", "applause"] },
    { char: "🙂", codes: ["slightly_smiling_face", "slight_smile"] },
    { char: "😐", codes: ["neutral_face", "meh"] },
    { char: "😑", codes: ["expressionless", "blank"] },
    { char: "😶", codes: ["no_mouth", "silent"] },
    { char: "🤫", codes: ["shushing_face", "shh"] },
    { char: "😬", codes: ["grimacing", "yikes"] },
    { char: "😮‍💨", codes: ["face_exhaling", "whew", "relief"] },
    { char: "🥱", codes: ["yawning_face", "boring"] },
    { char: "😴", codes: ["sleeping", "tired", "zzz"] },
    { char: "🤤", codes: ["drooling"] },
    { char: "😪", codes: ["sleepy"] },
    { char: "😵", codes: ["dizzy_face", "dead"] },
    { char: "😵‍💫", codes: ["face_with_spiral_eyes"] },
    { char: "🤐", codes: ["zipper_mouth", "secret"] },
    { char: "🥴", codes: ["woozy", "tipsy"] },
    { char: "🤢", codes: ["nauseated", "sick"] },
    { char: "🤮", codes: ["vomiting", "puke"] },
    { char: "🤧", codes: ["sneezing"] },
    { char: "😷", codes: ["mask", "sick_face"] },
    { char: "🤒", codes: ["thermometer_face", "fever"] },
    { char: "🤕", codes: ["head_bandage", "hurt"] },
    { char: "🥺", codes: ["pleading", "puppy_eyes"] },
    { char: "🤯", codes: ["exploding_head", "mind_blown"] },
    { char: "🤩", codes: ["star_struck", "amazing"] },
    { char: "🥳", codes: ["partying_face", "celebration"] },
    { char: "😎", codes: ["sunglasses", "cool"] },
    { char: "🤓", codes: ["nerd", "geek"] },
    { char: "🧐", codes: ["monocle", "inspecting"] },
    { char: "😕", codes: ["confused"] },
    { char: "😟", codes: ["worried"] },
    { char: "🙁", codes: ["slightly_frowning"] },
    { char: "☹️", codes: ["frowning"] },
    { char: "😮", codes: ["open_mouth", "surprised"] },
    { char: "😯", codes: ["hushed"] },
    { char: "😲", codes: ["astonished"] },
    { char: "😳", codes: ["flushed", "blushing"] },
    { char: "🥵", codes: ["hot_face", "sweating"] },
    { char: "🥶", codes: ["cold_face", "freezing"] },
    { char: "😨", codes: ["fearful", "scared"] },
    { char: "😰", codes: ["anxious", "sweat"] },
    { char: "😥", codes: ["disappointed_relieved"] },
    { char: "😓", codes: ["sweat", "hard_work"] },
    { char: "🤥", codes: ["lying_face", "pinocchio"] },
    { char: "😶‍🌫️", codes: ["face_in_clouds"] },
    { char: "😌", codes: ["relieved"] },
    { char: "😔", codes: ["pensive"] },
    { char: "😛", codes: ["stuck_out_tongue", "tongue"] },
    { char: "😜", codes: ["winking_tongue"] },
    { char: "🤪", codes: ["zany_face", "crazy"] },
    { char: "😝", codes: ["squinting_tongue"] },
    { char: "🤑", codes: ["money_mouth", "rich"] },
    { char: "🤨", codes: ["raised_eyebrow", "skeptical"] },
    { char: "🐛", codes: ["bug", "caterpillar"] },
    { char: "🔧", codes: ["wrench", "fix"] },
    { char: "📝", codes: ["memo", "note", "writing"] },
    { char: "⌛", codes: ["hourglass", "time"] },
    { char: "⏳", codes: ["hourglass_flowing", "loading"] },
    { char: "🔍", codes: ["mag", "search", "zoom"] },
    { char: "📌", codes: ["pushpin", "pin"] },
    { char: "✂️", codes: ["scissors", "cut"] },
    { char: "🔗", codes: ["link"] },
    { char: "📎", codes: ["paperclip", "attach"] },
    { char: "🖇️", codes: ["linked_paperclips"] },
    { char: "📏", codes: ["straight_ruler"] },
    { char: "📐", codes: ["triangular_ruler"] },
    { char: "✏️", codes: ["pencil"] },
    { char: "✒️", codes: ["black_nib"] },
    { char: "🖊️", codes: ["pen"] },
    { char: "🖋️", codes: ["fountain_pen"] },
    { char: "🖌️", codes: ["paintbrush"] },
    { char: "🖍️", codes: ["crayon"] },
    { char: "📋", codes: ["clipboard"] },
    { char: "🗂️", codes: ["card_index_dividers"] },
    { char: "📁", codes: ["file_folder"] },
    { char: "📂", codes: ["open_file_folder"] },
    { char: "🗃️", codes: ["card_file_box"] },
    { char: "🗄️", codes: ["file_cabinet"] },
    { char: "🗑️", codes: ["wastebasket", "trash", "delete"] },
    { char: "🔒", codes: ["lock", "secure", "private"] },
    { char: "🔓", codes: ["unlock"] },
    { char: "🔏", codes: ["lock_with_pen", "signed"] },
    { char: "🔐", codes: ["closed_lock_with_key"] },
    { char: "🔑", codes: ["key", "password"] },
    { char: "🗝️", codes: ["old_key"] },
    { char: "🔨", codes: ["hammer"] },
    { char: "🪓", codes: ["axe"] },
    { char: "⛏️", codes: ["pick"] },
    { char: "⚒️", codes: ["hammer_and_pick"] },
    { char: "🛠️", codes: ["hammer_and_wrench"] },
    { char: "🗡️", codes: ["dagger"] },
    { char: "⚔️", codes: ["crossed_swords"] },
    { char: "💣", codes: ["bomb", "deploy"] },
    { char: "🧨", codes: ["dynamite"] },
    { char: "🪃", codes: ["boomerang"] },
    { char: "🏹", codes: ["bow_and_arrow"] },
    { char: "🛡️", codes: ["shield"] },
    { char: "🔬", codes: ["microscope", "investigate"] },
    { char: "🔭", codes: ["telescope"] },
    { char: "📡", codes: ["satellite"] },
    { char: "💉", codes: ["syringe"] },
    { char: "🩸", codes: ["blood"] },
    { char: "💊", codes: ["pill"] },
    { char: "🧬", codes: ["dna"] },
    { char: "🦠", codes: ["microbe", "virus"] },
    { char: "🧫", codes: ["petri_dish"] },
    { char: "🧪", codes: ["test_tube"] },
    { char: "🌡️", codes: ["thermometer"] },
    { char: "🧹", codes: ["broom", "clean"] },
    { char: "🧺", codes: ["basket"] },
    { char: "🧻", codes: ["toilet_paper", "roll"] },
    { char: "🚽", codes: ["toilet"] },
    { char: "🚿", codes: ["shower"] },
    { char: "🛁", codes: ["bathtub"] },
    { char: "🪥", codes: ["toothbrush"] },
    { char: "🪒", codes: ["razor"] },
    { char: "🧴", codes: ["lotion"] },
    { char: "🧷", codes: ["safety_pin"] },
    { char: "🧵", codes: ["thread"] },
    { char: "🪡", codes: ["needle"] },
    { char: "🧶", codes: ["yarn"] },
    { char: "🧢", codes: ["cap", "hat"] },
    { char: "👒", codes: ["womans_hat"] },
    { char: "🎓", codes: ["mortar_board", "graduation"] },
    { char: "⛑️", codes: ["rescue_worker_helmet"] },
    { char: "👑", codes: ["crown"] },
    { char: "💍", codes: ["ring"] },
    { char: "💎", codes: ["gem", "diamond"] },
    { char: "🤖", codes: ["robot", "bot"] },
    { char: "👽", codes: ["alien"] },
    { char: "👾", codes: ["space_invader", "retro"] },
    { char: "👻", codes: ["ghost", "spooky"] },
    { char: "💀", codes: ["skull", "dead"] },
    { char: "☠️", codes: ["skull_and_crossbones", "danger"] },
    { char: "💩", codes: ["poop", "shit", "crap"] },
    { char: "🤠", codes: ["cowboy"] },
    { char: "🦾", codes: ["mechanical_arm"] },
    { char: "🦿", codes: ["mechanical_leg"] },
    { char: "🦻", codes: ["ear_with_hearing_aid"] },
    { char: "🧏", codes: ["deaf_person"] },
    { char: "🦯", codes: ["probing_cane"] },
    { char: "🦮", codes: ["guide_dog"] },
    { char: "🐕‍🦺", codes: ["service_dog"] },
    { char: "🐈‍⬛", codes: ["black_cat"] },
    { char: "🐕", codes: ["dog"] },
    { char: "🐈", codes: ["cat"] },
    { char: "🐒", codes: ["monkey"] },
    { char: "🦍", codes: ["gorilla"] },
    { char: "🦧", codes: ["orangutan"] },
    { char: "🐶", codes: ["puppy"] },
    { char: "🐱", codes: ["kitten"] },
    { char: "🦊", codes: ["fox"] },
    { char: "🐻", codes: ["bear"] },
    { char: "🐼", codes: ["panda"] },
    { char: "🐨", codes: ["koala"] },
    { char: "🐯", codes: ["tiger"] },
    { char: "🍔", codes: ["burger", "hamburger"] },
    { char: "🍕", codes: ["pizza"] },
    { char: "☕", codes: ["coffee"] },
    { char: "🍺", codes: ["beer"] },
    { char: "🍷", codes: ["wine"] },
    { char: "🍜", codes: ["ramen", "noodles"] },
    { char: "🍣", codes: ["sushi"] },
    { char: "🌮", codes: ["taco"] },
    { char: "🎂", codes: ["cake", "birthday"] },
    { char: "🧁", codes: ["cupcake"] },
    { char: "🍪", codes: ["cookie"] },
    { char: "🍩", codes: ["doughnut"] },
    { char: "🍿", codes: ["popcorn"] },
    { char: "🧀", codes: ["cheese"] },
    { char: "🤦", codes: ["facepalm"] },
    { char: "🤦‍♂️", codes: ["man_facepalming"] },
    { char: "🤦‍♀️", codes: ["woman_facepalming"] },
    { char: "🤷", codes: ["shrug"] },
    { char: "🤷‍♂️", codes: ["man_shrugging"] },
    { char: "🤷‍♀️", codes: ["woman_shrugging"] },
    { char: "🤞", codes: ["crossed_fingers", "fingers_crossed"] },
    { char: "🤟", codes: ["love_you_gesture", "ily"] },
    { char: "🤘", codes: ["metal", "rock_on", "sign_of_the_horns"] },
    { char: "👆", codes: ["point_up"] },
    { char: "👇", codes: ["point_down"] },
    { char: "👈", codes: ["point_left"] },
    { char: "👉", codes: ["point_right"] },
    { char: "✌️", codes: ["v", "peace", "victory"] },
    { char: "🤙", codes: ["call_me", "shaka"] },
    { char: "💅", codes: ["nail_care", "nails"] },
    { char: "🤳", codes: ["selfie"] },
    { char: "💃", codes: ["dancer", "dancing"] },
    { char: "🕺", codes: ["man_dancing"] },
    { char: "🦸", codes: ["superhero"] },
    { char: "🦹", codes: ["supervillain"] },
    { char: "🧑‍💻", codes: ["technologist", "dev", "coder"] },
    { char: "👨‍💻", codes: ["man_technologist", "male_dev"] },
    { char: "👩‍💻", codes: ["woman_technologist", "female_dev"] },
    { char: "🧑‍🎨", codes: ["artist"] },
    { char: "🧑‍🔬", codes: ["scientist"] },
    { char: "🧑‍🏫", codes: ["teacher"] },
    { char: "🧑‍🎤", codes: ["singer"] },
    { char: "🧑‍🍳", codes: ["cook"] },
    { char: "🧑‍🚀", codes: ["astronaut"] },
    { char: "🧑‍🚒", codes: ["firefighter"] },
    { char: "👮", codes: ["police", "cop"] },
    { char: "🕵️", codes: ["detective", "sleuth"] },
    { char: "💂", codes: ["guard"] },
    { char: "🥷", codes: ["ninja"] },
    { char: "👷", codes: ["construction_worker"] },
    { char: "🧑‍🌾", codes: ["farmer"] },
    { char: "🤴", codes: ["prince"] },
    { char: "👸", codes: ["princess"] },
    { char: "🫅", codes: ["person_with_crown"] },
    { char: "🧙", codes: ["mage", "wizard"] },
    { char: "🧚", codes: ["fairy"] },
    { char: "🧛", codes: ["vampire"] },
    { char: "🧜", codes: ["merperson", "mermaid"] },
    { char: "🧝", codes: ["elf"] },
    { char: "🧞", codes: ["genie"] },
    { char: "🧟", codes: ["zombie"] },
    { char: "💆", codes: ["massage"] },
    { char: "💇", codes: ["haircut"] },
    { char: "🧖", codes: ["sauna", "steam"] },
    { char: "🤰", codes: ["pregnant"] },
    { char: "🤱", codes: ["breastfeeding"] },
    { char: "🍼", codes: ["baby_bottle"] },
    { char: "👶", codes: ["baby"] },
    { char: "👧", codes: ["girl"] },
    { char: "👦", codes: ["boy"] },
    { char: "🧒", codes: ["child"] },
    { char: "👴", codes: ["old_man", "grandpa"] },
    { char: "👵", codes: ["old_woman", "grandma"] },
    { char: "🐶", codes: ["dog"] },
    { char: "🐱", codes: ["cat"] },
    { char: "🐭", codes: ["mouse"] },
    { char: "🐹", codes: ["hamster"] },
    { char: "🐰", codes: ["rabbit"] },
    { char: "🦊", codes: ["fox"] },
    { char: "🐻", codes: ["bear"] },
    { char: "🐼", codes: ["panda"] },
    { char: "🐻‍❄️", codes: ["polar_bear"] },
    { char: "🐨", codes: ["koala"] },
    { char: "🐯", codes: ["tiger"] },
    { char: "🦁", codes: ["lion"] },
    { char: "🐮", codes: ["cow"] },
    { char: "🐷", codes: ["pig"] },
    { char: "🐸", codes: ["frog"] },
    { char: "🐵", codes: ["monkey_face"] },
    { char: "🦄", codes: ["unicorn"] },
    { char: "🐴", codes: ["horse"] },
    { char: "🦓", codes: ["zebra"] },
    { char: "🐔", codes: ["chicken"] },
    { char: "🐧", codes: ["penguin"] },
    { char: "🐦", codes: ["bird"] },
    { char: "🦅", codes: ["eagle"] },
    { char: "🦉", codes: ["owl"] },
    { char: "🐝", codes: ["bee"] },
    { char: "🐞", codes: ["ladybug", "lady_beetle"] },
    { char: "🦋", codes: ["butterfly"] },
    { char: "🐌", codes: ["snail"] },
    { char: "🐛", codes: ["bug", "caterpillar"] },
    { char: "🐜", codes: ["ant"] },
    { char: "🦗", codes: ["cricket"] },
    { char: "🕷️", codes: ["spider"] },
    { char: "🦂", codes: ["scorpion"] },
    { char: "🐍", codes: ["snake"] },
    { char: "🦎", codes: ["lizard"] },
    { char: "🐢", codes: ["turtle"] },
    { char: "🐙", codes: ["octopus"] },
    { char: "🦑", codes: ["squid"] },
    { char: "🦐", codes: ["shrimp"] },
    { char: "🐠", codes: ["tropical_fish"] },
    { char: "🐟", codes: ["fish"] },
    { char: "🐡", codes: ["blowfish"] },
    { char: "🐬", codes: ["dolphin"] },
    { char: "🐳", codes: ["whale"] },
    { char: "🐊", codes: ["crocodile"] },
    { char: "🐉", codes: ["dragon"] },
    { char: "🦕", codes: ["sauropod", "brachiosaurus"] },
    { char: "🦖", codes: ["trex", "t_rex"] },
    { char: "🌵", codes: ["cactus"] },
    { char: "🎄", codes: ["christmas_tree", "xmastree"] },
    { char: "🌲", codes: ["evergreen_tree"] },
    { char: "🌳", codes: ["deciduous_tree"] },
    { char: "🌴", codes: ["palm_tree"] },
    { char: "🌱", codes: ["seedling"] },
    { char: "🌿", codes: ["herb"] },
    { char: "☘️", codes: ["shamrock"] },
    { char: "🍀", codes: ["four_leaf_clover", "luck"] },
    { char: "🌸", codes: ["cherry_blossom"] },
    { char: "🌺", codes: ["hibiscus"] },
    { char: "🌻", codes: ["sunflower"] },
    { char: "🌹", codes: ["rose"] },
    { char: "🥀", codes: ["wilted_rose"] },
    { char: "🌷", codes: ["tulip"] },
    { char: "💐", codes: ["bouquet"] },
    { char: "🍄", codes: ["mushroom"] },
    { char: "🌰", codes: ["chestnut"] },
    { char: "🦀", codes: ["crab"] },
    { char: "🦞", codes: ["lobster"] },
    { char: "🌈", codes: ["rainbow"] },
    { char: "☀️", codes: ["sunny", "sun"] },
    { char: "🌤️", codes: ["sun_behind_small_cloud"] },
    { char: "⛅", codes: ["partly_sunny"] },
    { char: "🌥️", codes: ["sun_behind_large_cloud"] },
    { char: "☁️", codes: ["cloud"] },
    { char: "🌧️", codes: ["rain"] },
    { char: "⛈️", codes: ["thunderstorm"] },
    { char: "🌩️", codes: ["lightning"] },
    { char: "🌨️", codes: ["snow"] },
    { char: "❄️", codes: ["snowflake"] },
    { char: "☃️", codes: ["snowman"] },
    { char: "⛄", codes: ["snowman_without_snow"] },
    { char: "🌬️", codes: ["wind"] },
    { char: "💨", codes: ["dash", "fast", "whoosh"] },
    { char: "🌪️", codes: ["tornado"] },
    { char: "🌊", codes: ["ocean", "wave"] },
    { char: "💧", codes: ["droplet", "water"] },
    { char: "🔥", codes: ["fire", "hot", "lit"] },
    { char: "💥", codes: ["boom", "explosion", "collision"] },
    { char: "✨", codes: ["sparkles", "shine"] },
    { char: "🌟", codes: ["glowing_star"] },
    { char: "⭐", codes: ["star"] },
    { char: "🌙", codes: ["crescent_moon"] },
    { char: "☄️", codes: ["comet"] },
    { char: "🌍", codes: ["earth_africa"] },
    { char: "🌎", codes: ["earth_americas"] },
    { char: "🌏", codes: ["earth_asia"] },
    { char: "🪐", codes: ["ringed_planet", "saturn"] },
    { char: "🍏", codes: ["green_apple"] },
    { char: "🍎", codes: ["apple", "red_apple"] },
    { char: "🍐", codes: ["pear"] },
    { char: "🍊", codes: ["orange", "tangerine"] },
    { char: "🍋", codes: ["lemon"] },
    { char: "🍌", codes: ["banana"] },
    { char: "🍉", codes: ["watermelon"] },
    { char: "🍇", codes: ["grapes"] },
    { char: "🍓", codes: ["strawberry"] },
    { char: "🫐", codes: ["blueberries"] },
    { char: "🍒", codes: ["cherries"] },
    { char: "🍑", codes: ["peach"] },
    { char: "🥭", codes: ["mango"] },
    { char: "🍍", codes: ["pineapple"] },
    { char: "🥥", codes: ["coconut"] },
    { char: "🥝", codes: ["kiwi"] },
    { char: "🍅", codes: ["tomato"] },
    { char: "🥑", codes: ["avocado"] },
    { char: "🥒", codes: ["cucumber"] },
    { char: "🥬", codes: ["leafy_greens", "lettuce"] },
    { char: "🥦", codes: ["broccoli"] },
    { char: "🧄", codes: ["garlic"] },
    { char: "🧅", codes: ["onion"] },
    { char: "🥔", codes: ["potato"] },
    { char: "🥕", codes: ["carrot"] },
    { char: "🌽", codes: ["corn"] },
    { char: "🌶️", codes: ["hot_pepper", "chili"] },
    { char: "🫑", codes: ["bell_pepper"] },
    { char: "🥜", codes: ["peanuts"] },
    { char: "🍞", codes: ["bread"] },
    { char: "🥐", codes: ["croissant"] },
    { char: "🥖", codes: ["baguette"] },
    { char: "🥨", codes: ["pretzel"] },
    { char: "🥯", codes: ["bagel"] },
    { char: "🥞", codes: ["pancakes"] },
    { char: "🧇", codes: ["waffle"] },
    { char: "🧈", codes: ["butter"] },
    { char: "🥚", codes: ["egg"] },
    { char: "🥓", codes: ["bacon"] },
    { char: "🥩", codes: ["steak", "meat"] },
    { char: "🍗", codes: ["poultry_leg", "chicken_leg"] },
    { char: "🍖", codes: ["meat_on_bone"] },
    { char: "🍤", codes: ["fried_shrimp"] },
    { char: "🥡", codes: ["takeout_box"] },
    { char: "🍚", codes: ["rice"] },
    { char: "🍝", codes: ["spaghetti", "pasta"] },
    { char: "🥗", codes: ["salad"] },
    { char: "🍲", codes: ["stew", "pot_of_food"] },
    { char: "🥫", codes: ["canned_food"] },
    { char: "🍱", codes: ["bento"] },
    { char: "🥮", codes: ["moon_cake"] },
    { char: "🍡", codes: ["dango"] },
    { char: "🥟", codes: ["dumpling"] },
    { char: "🍦", codes: ["icecream", "ice_cream"] },
    { char: "🍧", codes: ["shaved_ice"] },
    { char: "🍨", codes: ["ice_cream"] },
    { char: "🍰", codes: ["cake_slice", "shortcake"] },
    { char: "🧁", codes: ["cupcake"] },
    { char: "🥧", codes: ["pie"] },
    { char: "🍫", codes: ["chocolate"] },
    { char: "🍬", codes: ["candy"] },
    { char: "🍭", codes: ["lollipop"] },
    { char: "🍯", codes: ["honey"] },
    { char: "🧋", codes: ["bubble_tea", "boba"] },
    { char: "🍵", codes: ["tea"] },
    { char: "🧃", codes: ["juice_box"] },
    { char: "🥤", codes: ["cup_with_straw"] },
    { char: "🧊", codes: ["ice"] },
    { char: "🥢", codes: ["chopsticks"] },
    { char: "🍽️", codes: ["plate", "dinner"] },
    { char: "🥄", codes: ["spoon"] },
    { char: "🔪", codes: ["knife"] },
    { char: "🏠", codes: ["house"] },
    { char: "🏡", codes: ["house_with_garden"] },
    { char: "🏢", codes: ["office", "building"] },
    { char: "🏥", codes: ["hospital"] },
    { char: "🏦", codes: ["bank"] },
    { char: "🏫", codes: ["school"] },
    { char: "🏪", codes: ["convenience_store"] },
    { char: "⛪", codes: ["church"] },
    { char: "🕌", codes: ["mosque"] },
    { char: "🕍", codes: ["synagogue"] },
    { char: "🏛️", codes: ["classical_building"] },
    { char: "⛺", codes: ["tent", "camping"] },
    { char: "🚗", codes: ["car", "auto"] },
    { char: "🚕", codes: ["taxi"] },
    { char: "🚙", codes: ["suv"] },
    { char: "🚌", codes: ["bus"] },
    { char: "🚎", codes: ["trolleybus"] },
    { char: "🏎️", codes: ["race_car", "f1"] },
    { char: "🚓", codes: ["police_car"] },
    { char: "🚑", codes: ["ambulance"] },
    { char: "🚒", codes: ["fire_engine", "fire_truck"] },
    { char: "🚜", codes: ["tractor"] },
    { char: "🛻", codes: ["pickup_truck"] },
    { char: "🏍️", codes: ["motorcycle", "motorbike"] },
    { char: "🛵", codes: ["scooter"] },
    { char: "🚲", codes: ["bicycle", "bike"] },
    { char: "🛴", codes: ["kick_scooter"] },
    { char: "🛹", codes: ["skateboard"] },
    { char: "✈️", codes: ["airplane", "flight"] },
    { char: "🚁", codes: ["helicopter"] },
    { char: "🛸", codes: ["ufo", "flying_saucer"] },
    { char: "🚀", codes: ["rocket", "ship", "deploy"] },
    { char: "🛰️", codes: ["satellite_orbital"] },
    { char: "⛵", codes: ["sailboat"] },
    { char: "🚤", codes: ["speedboat"] },
    { char: "🛳️", codes: ["passenger_ship", "cruise"] },
    { char: "⛴️", codes: ["ferry"] },
    { char: "🚢", codes: ["ship"] },
    { char: "⚓", codes: ["anchor"] },
    { char: "🚧", codes: ["construction", "wip"] },
    { char: "⛽", codes: ["fuel_pump", "gas"] },
    { char: "🚏", codes: ["bus_stop"] },
    { char: "🚦", codes: ["traffic_light"] },
    { char: "🚥", codes: ["horizontal_traffic_light"] },
    { char: "🛑", codes: ["stop_sign"] },
    { char: "⌚", codes: ["watch"] },
    { char: "📱", codes: ["phone", "mobile", "iphone"] },
    { char: "💻", codes: ["laptop", "computer", "pc"] },
    { char: "⌨️", codes: ["keyboard"] },
    { char: "🖥️", codes: ["desktop"] },
    { char: "🖨️", codes: ["printer"] },
    { char: "🖱️", codes: ["mouse_computer"] },
    { char: "💾", codes: ["floppy_disk"] },
    { char: "💿", codes: ["cd"] },
    { char: "📀", codes: ["dvd"] },
    { char: "🎥", codes: ["movie_camera"] },
    { char: "📹", codes: ["video_camera"] },
    { char: "📷", codes: ["camera"] },
    { char: "📸", codes: ["camera_with_flash"] },
    { char: "📺", codes: ["tv", "television"] },
    { char: "📻", codes: ["radio"] },
    { char: "🎙️", codes: ["microphone_studio"] },
    { char: "🎚️", codes: ["level_slider"] },
    { char: "🎛️", codes: ["control_knobs"] },
    { char: "⏱️", codes: ["stopwatch"] },
    { char: "⏲️", codes: ["timer_clock"] },
    { char: "⏰", codes: ["alarm_clock"] },
    { char: "🕰️", codes: ["mantelpiece_clock"] },
    { char: "🧭", codes: ["compass"] },
    { char: "💸", codes: ["money_with_wings", "spend"] },
    { char: "💰", codes: ["money_bag", "rich", "cash"] },
    { char: "💳", codes: ["credit_card"] },
    { char: "💴", codes: ["yen"] },
    { char: "💵", codes: ["dollar"] },
    { char: "💶", codes: ["euro"] },
    { char: "💷", codes: ["pound"] },
    { char: "🪙", codes: ["coin"] },
    { char: "📊", codes: ["bar_chart"] },
    { char: "📈", codes: ["chart_up", "growth"] },
    { char: "📉", codes: ["chart_down", "decline"] },
    { char: "🗳️", codes: ["ballot_box"] },
    { char: "🔖", codes: ["bookmark"] },
    { char: "🏷️", codes: ["label", "tag"] },
    { char: "💰", codes: ["money_bag", "rich", "cash"] },
    { char: "🏆", codes: ["trophy", "winner"] },
    { char: "🥇", codes: ["gold_medal", "first"] },
    { char: "🥈", codes: ["silver_medal", "second"] },
    { char: "🥉", codes: ["bronze_medal", "third"] },
    { char: "🎖️", codes: ["medal"] },
    { char: "🏅", codes: ["sports_medal"] },
    { char: "🎗️", codes: ["ribbon"] },
    { char: "🔔", codes: ["bell"] },
    { char: "🔕", codes: ["no_bell", "mute"] },
    { char: "🎵", codes: ["musical_note"] },
    { char: "🎶", codes: ["notes", "music"] },
    { char: "🎼", codes: ["musical_score"] },
    { char: "🎤", codes: ["microphone", "mic"] },
    { char: "🎧", codes: ["headphones"] },
    { char: "🎷", codes: ["saxophone"] },
    { char: "🎸", codes: ["guitar"] },
    { char: "🎹", codes: ["piano", "keyboard_musical"] },
    { char: "🎺", codes: ["trumpet"] },
    { char: "🎻", codes: ["violin"] },
    { char: "🥁", codes: ["drum"] },
    { char: "🎬", codes: ["clapper", "action"] },
    { char: "🎮", codes: ["video_game", "controller"] },
    { char: "🎲", codes: ["die", "dice"] },
    { char: "♟️", codes: ["chess_pawn"] },
    { char: "🎯", codes: ["dart", "bullseye", "target"] },
    { char: "🎳", codes: ["bowling"] },
    { char: "🎿", codes: ["ski"] },
    { char: "⛷️", codes: ["skier"] },
    { char: "🏂", codes: ["snowboarder"] },
    { char: "🏋️", codes: ["weight_lifting"] },
    { char: "🤺", codes: ["fencing"] },
    { char: "⛳", codes: ["golf"] },
    { char: "🏄", codes: ["surfing"] },
    { char: "🚣", codes: ["rowing"] },
    { char: "🏊", codes: ["swimming"] },
    { char: "🚴", codes: ["cycling"] },
    { char: "🚵", codes: ["mountain_biking"] },
    { char: "🧗", codes: ["climbing"] },
    { char: "🤸", codes: ["cartwheel", "gymnastics"] },
    { char: "🤾", codes: ["handball"] },
    { char: "🤹", codes: ["juggling"] },
    { char: "🧘", codes: ["yoga", "meditation"] },
    { char: "🎪", codes: ["circus"] },
    { char: "🎭", codes: ["performing_arts", "theater"] },
    { char: "🎨", codes: ["art", "palette"] },
    { char: "🎰", codes: ["slot_machine"] },
    { char: "🚂", codes: ["train", "locomotive"] },
    { char: "🚆", codes: ["train2"] },
    { char: "🚇", codes: ["metro", "subway"] },
    { char: "🚊", codes: ["tram"] },
    { char: "🚝", codes: ["monorail"] },
    { char: "🚞", codes: ["mountain_railway"] },
    { char: "🚋", codes: ["train_car"] },
    { char: "🚈", codes: ["light_rail"] },
    { char: "🚅", codes: ["bullet_train", "shinkansen"] },
    { char: "🚄", codes: ["high_speed_train"] },
    { char: "💺", codes: ["seat"] },
    { char: "🧳", codes: ["luggage", "suitcase"] },
    { char: "🎒", codes: ["backpack"] },
    { char: "👟", codes: ["sneaker", "shoe"] },
    { char: "👠", codes: ["high_heel"] },
    { char: "👡", codes: ["sandal"] },
    { char: "👢", codes: ["boot"] },
    { char: "🩴", codes: ["flip_flop", "thong_sandal"] },
    { char: "👞", codes: ["mans_shoe"] },
    { char: "🧤", codes: ["gloves"] },
    { char: "🧣", codes: ["scarf"] },
    { char: "🧥", codes: ["coat"] },
    { char: "👗", codes: ["dress"] },
    { char: "👘", codes: ["kimono"] },
    { char: "👙", codes: ["bikini"] },
    { char: "👚", codes: ["womans_clothes"] },
    { char: "👕", codes: ["shirt", "tshirt"] },
    { char: "👖", codes: ["jeans"] },
    { char: "🩳", codes: ["shorts"] },
    { char: "👔", codes: ["tie", "necktie"] },
    { char: "🕶️", codes: ["sunglasses_dark"] },
    { char: "🥽", codes: ["goggles"] },
    { char: "🥼", codes: ["lab_coat"] },
    { char: "🦺", codes: ["safety_vest"] },
    { char: "🩰", codes: ["ballet_shoes"] },
    { char: "🩱", codes: ["one_piece_swimsuit"] },
    { char: "🩲", codes: ["briefs"] },
    { char: "🩳", codes: ["shorts"] },
    { char: "💄", codes: ["lipstick"] },
    { char: "💋", codes: ["kiss"] },
    { char: "🧴", codes: ["lotion"] },
    { char: "🧼", codes: ["soap"] },
    { char: "🪥", codes: ["toothbrush"] },
    { char: "🪒", codes: ["razor"] },
    { char: "🧽", codes: ["sponge"] },
    { char: "🧯", codes: ["fire_extinguisher"] },
    { char: "🛒", codes: ["shopping_cart"] },
    { char: "🧿", codes: ["nazar_amulet", "evil_eye"] },
    { char: "🪬", codes: ["hamsa"] },
    { char: "📿", codes: ["prayer_beads"] },
    { char: "🪷", codes: ["lotus"] },
    { char: "♻️", codes: ["recycle"] },
    { char: "💚", codes: ["green_heart"] },
    { char: "💙", codes: ["blue_heart"] },
    { char: "💜", codes: ["purple_heart"] },
    { char: "💛", codes: ["yellow_heart"] },
    { char: "🧡", codes: ["orange_heart"] },
    { char: "🖤", codes: ["black_heart"] },
    { char: "🤍", codes: ["white_heart"] },
    { char: "🤎", codes: ["brown_heart"] },
    { char: "💔", codes: ["broken_heart"] },
    { char: "❣️", codes: ["heart_exclamation"] },
    { char: "💖", codes: ["sparkling_heart"] },
    { char: "💗", codes: ["growing_heart"] },
    { char: "💓", codes: ["beating_heart"] },
    { char: "💞", codes: ["revolving_hearts"] },
    { char: "💘", codes: ["heart_with_arrow", "cupid"] },
    { char: "💝", codes: ["gift_heart"] },
    { char: "💟", codes: ["heart_decoration"] },
    { char: "☮️", codes: ["peace_symbol"] },
    { char: "✝️", codes: ["cross_latin"] },
    { char: "☪️", codes: ["star_and_crescent"] },
    { char: "🕉️", codes: ["om"] },
    { char: "☸️", codes: ["wheel_of_dharma"] },
    { char: "✡️", codes: ["star_of_david"] },
    { char: "🔯", codes: ["six_pointed_star"] },
    { char: "🕎", codes: ["menorah"] },
    { char: "☯️", codes: ["yin_yang"] },
    { char: "☦️", codes: ["orthodox_cross"] },
    { char: "🛐", codes: ["place_of_worship"] },
    { char: "⚛️", codes: ["atom"] },
    { char: "🕉️", codes: ["om"] },
    { char: "✡️", codes: ["star_of_david"] },
    { char: "☸️", codes: ["wheel_of_dharma"] },
    { char: "☯️", codes: ["yin_yang"] },
    { char: "✝️", codes: ["cross_latin"] },
    { char: "☦️", codes: ["orthodox_cross"] },
    { char: "☪️", codes: ["star_and_crescent"] },
    { char: "☮️", codes: ["peace_symbol"] },
    { char: "🕎", codes: ["menorah"] },
    { char: "🔯", codes: ["six_pointed_star"] },
    { char: "♈", codes: ["aries"] },
    { char: "♉", codes: ["taurus"] },
    { char: "♊", codes: ["gemini"] },
    { char: "♋", codes: ["cancer"] },
    { char: "♌", codes: ["leo"] },
    { char: "♍", codes: ["virgo"] },
    { char: "♎", codes: ["libra"] },
    { char: "♏", codes: ["scorpio"] },
    { char: "♐", codes: ["sagittarius"] },
    { char: "♑", codes: ["capricorn"] },
    { char: "♒", codes: ["aquarius"] },
    { char: "♓", codes: ["pisces"] },
    { char: "⛎", codes: ["ophiuchus"] },
    { char: "🙈", codes: ["see_no_evil"] },
    { char: "🙉", codes: ["hear_no_evil"] },
    { char: "🙊", codes: ["speak_no_evil"] },
    { char: "💢", codes: ["anger", "vein"] },
    { char: "💬", codes: ["speech_bubble"] },
    { char: "👁️‍🗨️", codes: ["eye_in_speech_bubble"] },
    { char: "🗨️", codes: ["left_speech_bubble"] },
    { char: "🗯️", codes: ["anger_bubble", "shout"] },
    { char: "💭", codes: ["thought_bubble"] },
    { char: "💤", codes: ["zzz", "sleep"] },
    { char: "🧩", codes: ["puzzle_piece"] },
    { char: "♟️", codes: ["chess_pawn"] },
    { char: "🃏", codes: ["joker"] },
    { char: "🀄", codes: ["mahjong"] },
    { char: "🎴", codes: ["flower_playing_cards"] },
    { char: "🎭", codes: ["performing_arts", "theater"] },
    { char: "🖼️", codes: ["frame", "painting"] },
    { char: "🎨", codes: ["art", "palette"] },
    { char: "🧵", codes: ["thread"] },
    { char: "🪡", codes: ["needle"] },
    { char: "🧶", codes: ["yarn"] },
    { char: "🪢", codes: ["knot"] },
    { char: "🥅", codes: ["goal_net"] },
    { char: "⚽", codes: ["soccer", "football"] },
    { char: "🏀", codes: ["basketball"] },
    { char: "🏈", codes: ["football_american"] },
    { char: "⚾", codes: ["baseball"] },
    { char: "🥎", codes: ["softball"] },
    { char: "🎾", codes: ["tennis"] },
    { char: "🏐", codes: ["volleyball"] },
    { char: "🏉", codes: ["rugby"] },
    { char: "🥏", codes: ["frisbee"] },
    { char: "🎱", codes: ["8ball", "pool"] },
    { char: "🏓", codes: ["ping_pong"] },
    { char: "🏸", codes: ["badminton"] },
    { char: "🥊", codes: ["boxing_glove"] },
    { char: "🥋", codes: ["martial_arts_uniform"] },
    { char: "⛸️", codes: ["ice_skate"] },
    { char: "🥌", codes: ["curling_stone"] },
    { char: "🛷", codes: ["sled"] },
    { char: "🪂", codes: ["parachute"] },
    { char: "♠️", codes: ["spades"] },
    { char: "♥️", codes: ["hearts"] },
    { char: "♦️", codes: ["diamonds"] },
    { char: "♣️", codes: ["clubs"] },
];

// Index entries for fast prefix matching.
interface IndexEntry {
    readonly char: string;
    readonly match: string;
}

const index: IndexEntry[] = [];

for (const entry of EMOJIS) {
    for (const code of entry.codes) {
        index.push({ char: entry.char, match: code });
    }
}

const deduped: IndexEntry[] = [];
const seen = new Set<string>();
for (const entry of index) {
    const key = `${entry.char}|${entry.match}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(entry);
}

// Subsequence match: every character of `q` must appear in `target` in order,
// not necessarily consecutively. `midfin` matches "middle_finger" because
// m-i-d-f-i-n all exist in that order.
const isSubsequence = (q: string, target: string): boolean => {
    let ti = 0;
    for (let qi = 0; qi < q.length; qi++) {
        const qc = q[qi]!;
        ti = target.indexOf(qc, ti);
        if (ti < 0) return false;
        ti++;
    }
    return true;
};

// Fuzzy match: subsequence of the query in the shortcode. Sort by match length
// (shorter = tighter fit), with an exact prefix bonus so `:joy` ranks above
// `:japanese_ogre` when query is "jo".
export const searchEmojis = (query: string, maxResults: number): readonly IndexEntry[] => {
    const q = query.toLowerCase();
    const matches = deduped.filter((e) => isSubsequence(q, e.match));
    matches.sort((a, b) => {
        const aExact = a.match.startsWith(q) ? 0 : 1;
        const bExact = b.match.startsWith(q) ? 0 : 1;
        if (aExact !== bExact) return aExact - bExact;
        return a.match.length - b.match.length;
    });
    const result: IndexEntry[] = [];
    const used = new Set<string>();
    for (const m of matches) {
        if (used.has(m.char)) continue;
        used.add(m.char);
        result.push(m);
        if (result.length >= maxResults) break;
    }
    return result;
};
